name: Deploy

on:
  push:
    branches:
      - master 
  pull_request:
    branches: [master]
    types: [opened, synchronize] 

jobs:
  build:
    if: ${{ github.event_name == 'push' && !(contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'fullstack-pokedex-anna' #Must be unique in Heroku
          heroku_email: 'anna.nikander@aalto.fi'
          remote_branch: master
          healthcheck: 'https://fullstack-pokedex-anna.herokuapp.com/health'
          checkstring: 'ok'
          #delay: 30
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
      - name: successful slack message
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `a new version deployed to https://fullstack-pokedex-anna.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: failed slack message
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required