name: Scheduled healthcheck

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.4
        with:
          # Check the following URLs one by one sequentially
          url: https://fullstack-pokedex-anna.herokuapp.com/
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: no # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 1 # Optional, defaults to 1
          # Delay between retries
          #retry-delay: 5s # Optional, only applicable to max-attempts > 1